version: "3"
services:
api: 
    build: ./Dockerfile
    ports:	
    - "8080:5000"

web:
     build: .
     ports:
     - "8080:5000"

     links:
     - db

     volumes:
     - .:/javier

db:
     image: mysql
     environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: db
     MYSQL_USER: javier
     MYSQL_PASSWORD: javier
